; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
monitor_speed = 115200
framework = arduino
lib_deps = 
	smougenot/TM1637@0.0.0-alpha+sha.9486982048
	bblanchon/ArduinoJson@^7.4.1
	mobizt/FirebaseClient@^2.1.8
	arduino-libraries/NTPClient@^3.2.1
	jhagas/ESPSupabase@^0.1.0
	paulstoffregen/Time
	adafruit/RTClib@^2.1.4
src_dir = stage
build_src_filter = -<*> +<motor_schdule_supabase1.cpp>
